// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: zeus/v1/zeus.proto

package zeus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Zeus_ExecSoar_FullMethodName = "/zeus.v1.Zeus/ExecSoar"
)

// ZeusClient is the client API for Zeus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZeusClient interface {
	ExecSoar(ctx context.Context, in *ExecSoarRequest, opts ...grpc.CallOption) (*ExecSoarResponse, error)
}

type zeusClient struct {
	cc grpc.ClientConnInterface
}

func NewZeusClient(cc grpc.ClientConnInterface) ZeusClient {
	return &zeusClient{cc}
}

func (c *zeusClient) ExecSoar(ctx context.Context, in *ExecSoarRequest, opts ...grpc.CallOption) (*ExecSoarResponse, error) {
	out := new(ExecSoarResponse)
	err := c.cc.Invoke(ctx, Zeus_ExecSoar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZeusServer is the server API for Zeus service.
// All implementations must embed UnimplementedZeusServer
// for forward compatibility
type ZeusServer interface {
	ExecSoar(context.Context, *ExecSoarRequest) (*ExecSoarResponse, error)
	mustEmbedUnimplementedZeusServer()
}

// UnimplementedZeusServer must be embedded to have forward compatible implementations.
type UnimplementedZeusServer struct {
}

func (UnimplementedZeusServer) ExecSoar(context.Context, *ExecSoarRequest) (*ExecSoarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecSoar not implemented")
}
func (UnimplementedZeusServer) mustEmbedUnimplementedZeusServer() {}

// UnsafeZeusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZeusServer will
// result in compilation errors.
type UnsafeZeusServer interface {
	mustEmbedUnimplementedZeusServer()
}

func RegisterZeusServer(s grpc.ServiceRegistrar, srv ZeusServer) {
	s.RegisterService(&Zeus_ServiceDesc, srv)
}

func _Zeus_ExecSoar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecSoarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZeusServer).ExecSoar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zeus_ExecSoar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZeusServer).ExecSoar(ctx, req.(*ExecSoarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zeus_ServiceDesc is the grpc.ServiceDesc for Zeus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zeus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zeus.v1.Zeus",
	HandlerType: (*ZeusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecSoar",
			Handler:    _Zeus_ExecSoar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zeus/v1/zeus.proto",
}
