// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: zeus/soar.proto

package zeus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Soar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query      string `protobuf:"bytes,10,opt,name=query,proto3" json:"query,omitempty"`
	ReportType string `protobuf:"bytes,20,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
}

func (x *Soar) Reset() {
	*x = Soar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_soar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Soar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Soar) ProtoMessage() {}

func (x *Soar) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_soar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Soar.ProtoReflect.Descriptor instead.
func (*Soar) Descriptor() ([]byte, []int) {
	return file_zeus_soar_proto_rawDescGZIP(), []int{0}
}

func (x *Soar) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Soar) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

var File_zeus_soar_proto protoreflect.FileDescriptor

var file_zeus_soar_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x7a, 0x65, 0x75, 0x73, 0x2f, 0x73, 0x6f, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x7a, 0x65, 0x75, 0x73, 0x22, 0x3d, 0x0a, 0x04, 0x53, 0x6f, 0x61, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x6c, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x2e, 0x7a, 0x65,
	0x75, 0x73, 0x42, 0x09, 0x53, 0x6f, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x6f,
	0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x7a, 0x65, 0x75, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x7a, 0x65, 0x75,
	0x73, 0x3b, 0x7a, 0x65, 0x75, 0x73, 0xa2, 0x02, 0x03, 0x5a, 0x58, 0x58, 0xaa, 0x02, 0x04, 0x5a,
	0x65, 0x75, 0x73, 0xca, 0x02, 0x04, 0x5a, 0x65, 0x75, 0x73, 0xe2, 0x02, 0x10, 0x5a, 0x65, 0x75,
	0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x04,
	0x5a, 0x65, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zeus_soar_proto_rawDescOnce sync.Once
	file_zeus_soar_proto_rawDescData = file_zeus_soar_proto_rawDesc
)

func file_zeus_soar_proto_rawDescGZIP() []byte {
	file_zeus_soar_proto_rawDescOnce.Do(func() {
		file_zeus_soar_proto_rawDescData = protoimpl.X.CompressGZIP(file_zeus_soar_proto_rawDescData)
	})
	return file_zeus_soar_proto_rawDescData
}

var file_zeus_soar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zeus_soar_proto_goTypes = []interface{}{
	(*Soar)(nil), // 0: zeus.Soar
}
var file_zeus_soar_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zeus_soar_proto_init() }
func file_zeus_soar_proto_init() {
	if File_zeus_soar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zeus_soar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Soar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zeus_soar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zeus_soar_proto_goTypes,
		DependencyIndexes: file_zeus_soar_proto_depIdxs,
		MessageInfos:      file_zeus_soar_proto_msgTypes,
	}.Build()
	File_zeus_soar_proto = out.File
	file_zeus_soar_proto_rawDesc = nil
	file_zeus_soar_proto_goTypes = nil
	file_zeus_soar_proto_depIdxs = nil
}
