// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/v1/zeus.proto

package zeus

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Soar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query      string `protobuf:"bytes,10,opt,name=query,proto3" json:"query,omitempty"`
	ReportType string `protobuf:"bytes,20,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
}

func (x *Soar) Reset() {
	*x = Soar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_zeus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Soar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Soar) ProtoMessage() {}

func (x *Soar) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_zeus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Soar.ProtoReflect.Descriptor instead.
func (*Soar) Descriptor() ([]byte, []int) {
	return file_api_v1_zeus_proto_rawDescGZIP(), []int{0}
}

func (x *Soar) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Soar) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

type ExecSoarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Soar *Soar `protobuf:"bytes,1,opt,name=soar,proto3" json:"soar,omitempty"`
}

func (x *ExecSoarRequest) Reset() {
	*x = ExecSoarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_zeus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecSoarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSoarRequest) ProtoMessage() {}

func (x *ExecSoarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_zeus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSoarRequest.ProtoReflect.Descriptor instead.
func (*ExecSoarRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_zeus_proto_rawDescGZIP(), []int{1}
}

func (x *ExecSoarRequest) GetSoar() *Soar {
	if x != nil {
		return x.Soar
	}
	return nil
}

type ExecSoarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level string `protobuf:"bytes,10,opt,name=level,proto3" json:"level,omitempty"`
	Data  string `protobuf:"bytes,20,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExecSoarResponse) Reset() {
	*x = ExecSoarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_zeus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecSoarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSoarResponse) ProtoMessage() {}

func (x *ExecSoarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_zeus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSoarResponse.ProtoReflect.Descriptor instead.
func (*ExecSoarResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_zeus_proto_rawDescGZIP(), []int{2}
}

func (x *ExecSoarResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ExecSoarResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_api_v1_zeus_proto protoreflect.FileDescriptor

var file_api_v1_zeus_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x7a, 0x65, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x7a, 0x65, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x04, 0x53, 0x6f,
	0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x34, 0x0a, 0x0f, 0x45, 0x78, 0x65,
	0x63, 0x53, 0x6f, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04,
	0x73, 0x6f, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x7a, 0x65, 0x75,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x61, 0x72, 0x52, 0x04, 0x73, 0x6f, 0x61, 0x72, 0x22,
	0x3c, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63, 0x53, 0x6f, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x5e, 0x0a,
	0x04, 0x5a, 0x65, 0x75, 0x73, 0x12, 0x56, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63, 0x53, 0x6f, 0x61,
	0x72, 0x12, 0x18, 0x2e, 0x7a, 0x65, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63,
	0x53, 0x6f, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x7a, 0x65,
	0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x53, 0x6f, 0x61, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x22, 0x0d,
	0x2f, 0x7a, 0x65, 0x75, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x61, 0x72, 0x42, 0x26, 0x5a,
	0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x6f,
	0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x7a, 0x65, 0x75, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x3b, 0x7a, 0x65, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_zeus_proto_rawDescOnce sync.Once
	file_api_v1_zeus_proto_rawDescData = file_api_v1_zeus_proto_rawDesc
)

func file_api_v1_zeus_proto_rawDescGZIP() []byte {
	file_api_v1_zeus_proto_rawDescOnce.Do(func() {
		file_api_v1_zeus_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_zeus_proto_rawDescData)
	})
	return file_api_v1_zeus_proto_rawDescData
}

var file_api_v1_zeus_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_zeus_proto_goTypes = []interface{}{
	(*Soar)(nil),             // 0: zeus.v1.Soar
	(*ExecSoarRequest)(nil),  // 1: zeus.v1.ExecSoarRequest
	(*ExecSoarResponse)(nil), // 2: zeus.v1.ExecSoarResponse
}
var file_api_v1_zeus_proto_depIdxs = []int32{
	0, // 0: zeus.v1.ExecSoarRequest.soar:type_name -> zeus.v1.Soar
	1, // 1: zeus.v1.Zeus.ExecSoar:input_type -> zeus.v1.ExecSoarRequest
	2, // 2: zeus.v1.Zeus.ExecSoar:output_type -> zeus.v1.ExecSoarResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_zeus_proto_init() }
func file_api_v1_zeus_proto_init() {
	if File_api_v1_zeus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_zeus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Soar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_zeus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecSoarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_zeus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecSoarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_zeus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_zeus_proto_goTypes,
		DependencyIndexes: file_api_v1_zeus_proto_depIdxs,
		MessageInfos:      file_api_v1_zeus_proto_msgTypes,
	}.Build()
	File_api_v1_zeus_proto = out.File
	file_api_v1_zeus_proto_rawDesc = nil
	file_api_v1_zeus_proto_goTypes = nil
	file_api_v1_zeus_proto_depIdxs = nil
}
