logs:
  level: debug
  encode: console # json or console
  # output: file
  # initFields:
    # package: zeus.v1
    # server: zeus-server
    # version: v0.1.1
  file:
    path: ./logs/app.log
    maxSize: 100
    maxBackups: 10
    maxAge: 28
    encode: console
    # Compress: false
