// Code generated by fino. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date:

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"github.com/chaos-io/gokit/tracing"
	"github.com/go-kit/kit/log"
	grpctransport "github.com/go-kit/kit/transport/grpc"
	"go.opentelemetry.io/otel/trace"
	"google.golang.org/grpc/metadata"

	// this service api
	pb "github.com/chaos-io/zeus/api/v1"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC ZeusServer.
func MakeGRPCServer(endpoints Endpoints, tracer trace.Tracer, logger log.Logger) pb.ZeusServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
		grpctransport.ServerErrorLogger(logger),
	}

	addTracerOption := func(methodName string) []grpctransport.ServerOption {
		if tracer != nil {
			return append(serverOptions, grpctransport.ServerBefore(tracing.GRPCToContext(tracer, methodName)))
		}
		return serverOptions
	}

	return &grpcServer{
		// Zeus
		execSoar: grpctransport.NewServer(
			endpoints.ExecSoarEndpoint,
			DecodeGRPCExecSoarRequest,
			EncodeGRPCExecSoarResponse,
			addTracerOption("ExecSoar")...,
		),
	}
}

// grpcServer implements the ZeusServer interface
type grpcServer struct {
	pb.UnimplementedZeusServer

	execSoar grpctransport.Handler
}

// Methods for grpcServer to implement ZeusServer interface

func (s *grpcServer) ExecSoar(ctx context.Context, req *pb.ExecSoarRequest) (*pb.ExecSoarResponse, error) {
	_, rep, err := s.execSoar.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ExecSoarResponse), nil
}

// Server Decode

// DecodeGRPCExecSoarRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC ExecSoar request to a user-domain ExecSoar request. Primarily useful in a server.
func DecodeGRPCExecSoarRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.ExecSoarRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCExecSoarResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain ExecSoar response to a gRPC ExecSoar reply. Primarily useful in a server.
func EncodeGRPCExecSoarResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ExecSoarResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
