// Code generated by fino. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.1
// Version Date:

package main

import (
	"flag"

	"github.com/chaos-io/chaos/config"
	"github.com/chaos-io/chaos/logs"
	nserver "github.com/chaos-io/gokit/server"

	// This Service
	"github.com/chaos-io/zeus/service/internal"
)

var gitHash, gitBranch, buildTime string

func main() {
	flag.String("http_addr", ":20171", "default ip address for http server")
	flag.String("grpc_addr", ":20172", "default ip address for grpc server")
	flag.String("debug_addr", ":20173", "default ip address for debug server")

	// update addresses if they have been overwritten by flags
	flag.Parse()
	if err := config.LoadFlag(); err != nil {
		logs.Warnw("failed to load flag", "error", err)
	}

	var conf nserver.Config
	err := config.ScanFrom(&conf, "zeusServer", "server")
	if err != nil {
		logs.Warnw("failed to get the server config from config file", "error", err)
	}

	// read the value from flag, and will override the value from config file
	_ = config.ScanFrom(&conf.HttpAddr, "httpAddr")
	_ = config.ScanFrom(&conf.GrpcAddr, "grpcAddr")
	_ = config.ScanFrom(&conf.DebugAddr, "debugAddr")

	if len(gitHash) == 0 {
		logs.Infow("starting ZeusServer, you can use `-ldflags \"-X main.gitHash=xxx\" to generate gitHash")
	} else {
		logs.Infow("starting ZeusServer", "gitHash", gitHash, "gitBranch", gitBranch, "buildTime", buildTime)
	}

	internal.Run(conf)
}
